#!/bin/sh

PIDFILE=/var/run/shadowsocks.pid
LOGFILE=/var/log/shadowsocks.log

start(){
        ssserver -c /etc/shadowsocks/config.json -d start --fast-open --workers 3 --pid-file $PIDFILE --log-file $LOGFILE --user shadowsocks
}

stop(){
        ssserver -c /etc/shadowsocks/config.json -d stop
}

case "$1" in
start)
        start
        ;;
stop)
        stop
        ;;
reload)
        stop
        start
        ;;
*)
        echo "Usage: $0 {start|reload|stop}"
        exit 1
        ;;
esac
